### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lukepfjo** [ColinTimBarndt/wasm-gzip#1]
This project looks great, but I and many others will be unable to use it in public projects as no license is provided. Would you please consider adding a license?

If you are unfamiliar, popular options are:
[MIT (very permissive; what libflate uses)](https://tldrlegal.com/license/mit-license)
[Apache 2.0 (similarly permissive to MIT)](https://tldrlegal.com/license/apache-license-2.0-\(apache-2.0\))
[LGPL 3.0 (fairly restrictive; made for libraries)](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-\(lgpl-3\))

**Comment by ColinTimBarndt** [comment]
Thank you for the hint. I licensed this code under the Unlicense, so it can be used without any restrictions whatsoever as this is nothing more than glue code.
