### ISSUE TITLE
Support for multi-member gzip files?

### ISSUE THREAD

**Issue by aaronleopold** [ColinTimBarndt/wasm-gzip#3]
Hello! 

I was wondering if you had any plans to support multi-member gzip files? After some minimal investigation, it looks like it could just be a matter of allowing to specify the [`MultiDecoder`](https://github.com/sile/libflate/blob/6676d36d381eec60f376337e528d658b16c87c7a/src/gzip.rs#L1052C12-L1055) from the `libflate` library. I'm not sure if there are any other considerations to take into account, but wanted to see if there was any interest in supporting this.

Thanks!

**Comment by ColinTimBarndt** [comment]
I'll be looking into it!

**Comment by aaronleopold** [comment]
I appreciate you, thank you!
