### ISSUE TITLE
Document ways to set the compression level

### ISSUE THREAD

**Issue by mimi89999** [ColinTimBarndt/wasm-gzip#4]
Hello,

Would it be possible to document the way in which the compression level can be set?

**Comment by ColinTimBarndt** [comment]
It is currently not possible to specify the compression level. Libflate, which this library is wrapping, only provides [one LZ77 encoder for compression](https://docs.rs/libflate/latest/libflate/lz77/struct.DefaultLz77EncoderBuilder.html). At the moment, the default window size of it is the maximum (32768), so it is using the best compression level.

I could make the window size configurable and allow choosing a worse but faster compression that requires less memory. Is this what you're after?

**Comment by mimi89999** [comment]
Actually, I was looking for the best compression level. Since this is what the library is already doing, I don't need any options.
